# Generated by Django 4.1.3 on 2022-11-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_montgomerycountyparcels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MontgomeryCountyParcels',
            new_name='MontgomeryCountyParcel',
        ),
    ]
