# Generated by Django 4.1.3 on 2022-11-03 19:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_rename_montgomerycountyparcels_montgomerycountyparcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontgomeryCountyGeology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('original_l', models.CharField(blank=True, max_length=4, null=True)),
                ('sgmc_label', models.CharField(blank=True, max_length=9, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=52, null=True)),
                ('minimum_ag', models.CharField(blank=True, max_length=54, null=True)),
                ('maximum_ag', models.CharField(blank=True, max_length=54, null=True)),
                ('major_1', models.CharField(blank=True, max_length=12, null=True)),
                ('major_2', models.CharField(blank=True, max_length=8, null=True)),
                ('minor_1', models.CharField(blank=True, max_length=17, null=True)),
                ('minor_2', models.CharField(blank=True, max_length=22, null=True)),
                ('reference_field', models.CharField(blank=True, max_length=5, null=True)),
                ('reference', models.CharField(blank=True, max_length=233, null=True)),
                ('generalize', models.CharField(blank=True, max_length=41, null=True)),
                ('digital_ur', models.CharField(blank=True, max_length=74, null=True)),
                ('ngmdb1', models.CharField(blank=True, max_length=49, null=True)),
                ('shape_are', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
