# Generated by Django 4.1.3 on 2022-11-03 19:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_montgomerycountygeology'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontgomeryCountyWatershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('huc12', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=37, null=True)),
                ('shape_are', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
